previewsEnabled: true

envVarGroups:
  - name: ENV_SETTINGS
    envVars:
      - key: ATLAS_URL
        sync: false

services:
  # Node service
  - type: web
    name: chat-online
    env: node
    rootDir: src
    plan: free
    envVars:
      - fromGroup: ATLAS_SETTINGS
    buildCommand: npm install && npm run build
    startCommand: npm start
  - type: redis
    name: redis-service
    ipAllowList:
      - source: IP_ENV
    plan: free