previewsEnabled: true

envVarGroups:
  - name: ENV_SETTINGS
    envVars:
      - key: ATLAS_URL
        sync: false

services:
  # Node service
  - type: web
    name: chat-online
    env: node
    rootDir: src
    plan: free
    envVars:
      - fromGroup: ENV_SETTINGS
    buildCommand: npm install && npm run build
    startCommand: npm start