services:
  # A Docker web service
  - type: web
    name: chat-online
    env: node
    rootDir: src
    plan: free
    envVars:
      - key: ATLAS_URL
    buildCommand: npm install
    startCommand: npm start