services:
  # A Docker web service
  - type: web
    name: chat-online
    env: node
    rootDir: src
    plan: free
    key: ATLAS_URL
    sync: false
    buildCommand: npm install
    startCommand: npm start